version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/html
      - /var/www/html/node_modules
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodejs

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
      - /var/www/html/node_modules
    environment:
      DB_USERNAME: root
      DB_PASSWORD: secret
      DB_HOST: mongodb
    ports:
      - '3000:3000'
    restart: always

  mongodb:
    image: "mongo:4.4"
    volumes:
      - ./data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: businessCards
    ports:
      - "27017:27017"